version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: node:12.0.0
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test